# Enter the code at row 3010, column 3019.

# The first code is 20151125. After that, each code 
# is generated by taking the previous one, 
# multiplying it by 252533, and then keeping the remainder 
# from dividing that value by 33554393.

# numbers in the manual are 1-based
ROW = 3010
COL = 3019

START = 20151125
STEP_1 = 252533
STEP_2 = 33554393

def get_code(target, debug=False):
    target_row, target_col = target

    grid = []
    if debug:
        c = target_col * 2
        r = target_row * 2
        grid = [[0 for col in range(c)] for row in range(r)]

    c_row = 1
    c_col = 1
    row_count = 1
    c_code = START
    final_code = 0

    while final_code == 0:
        if c_row == target_row and c_col == target_col:
            final_code = c_code
        else:
            if debug:
                grid[c_row-1][c_col-1] = c_code
            c_code = (c_code * STEP_1) % STEP_2
            if c_row == 1:
                c_col = 1
                row_count += 1
                c_row = row_count
            else:
                c_col = c_col + 1
                c_row = c_row - 1
    if debug:
        for row in grid:
            print(' '.join([str(c) for c in row]))
    return c_code

# print(get_code(target=(6,6), debug=True))
print("Part 1:", get_code((ROW, COL)))

